name: Publish to npm

on:
  push:
    tags:
      - 'v*.*.*'  # Trigger only on version tags like v1.2.3

jobs:
  publish:
    name: Publish npm packages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # Using LTS version
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build packages
        run: yarn workspaces run build
        # This will build all packages in the workspace in the correct dependency order
        # If any package build fails, the whole workflow will fail

      - name: Publish packages
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
          # Loop through each package in packages directory
          for dir in packages/*; do
            if [ -f "$dir/package.json" ]; then
              echo "Publishing $dir"
              cd $dir
              # Check if the package is private
              IS_PRIVATE=$(node -p "require('./package.json').private")
              if [ "$IS_PRIVATE" != "true" ]; then
                npm publish --access public
                echo "✅ Published $dir"
              else
                echo "⏭️ Skipping private package $dir"
              fi
              cd ../../
            fi
          done
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
